### ISSUE TITLE
HOW TO FIX THIS ?

### ISSUE THREAD

**Issue by YashvirGaming** [nevioo1337/HTTPDebugger-Key-Generator#1]
Hello there , @nevioo1337  there seems to be multiple 82 errors how to fix this

UNABLE TO BUILD IN VS STUDIO 2022
I WON'T RUN YOUR PRE RELEASE EXE without knowing what's inside it. CANNOT RISK IT 

![image](https://github.com/nevioo1337/HTTPDebugger-Key-Generator/assets/64865096/828eb6d0-f8b7-4a2d-a1b2-bb8b267c2a12)

**Comment by nevioo1337** [comment]
Fix your Visual Studio C++ installation.
